---
- name: Create directories for Weather Applciation
  file: path={{ installLocation }} state=directory recurse=yes

- name: Download Weather Application
  get_url: url={{ downloadURL }} dest={{ installLocation }}/WeatherReport.zip

- name: Decompressed downloaded archive
  unarchive: src={{ installLocation }}/WeatherReport.zip dest={{ installLocation }} copy=no

- name: Remove downloaded archive
  file: path={{ installLocation }}/WeatherReport.zip state=absent

- name: Setup config for Weather Application
  template: src=config.properties.j2 dest={{ installLocation }}/WeatherReport/config.properties

- name: Setup startup script
  template: src=startup.sh.j2 dest={{ installLocation }}/WeatherReport/startup.sh
